name:                automata
version:             0.1.0.0
github:              "b-mehta/automata"
license:             BSD3
author:              "Bhavik Mehta"
maintainer:          "bhavikmehta8@gmail.com"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Simple cellular automata done comonadically
# category:            Web

description:         Please see the README on GitHub at <https://github.com/b-mehta/automata#readme>

dependencies:
- base >= 4.7 && < 5
- comonad >= 5
- random >= 1.1
- JuicyPixels >= 3.2
- vector >= 0.12
- containers >= 0.5.11
- optparse-applicative >= 0.14.2

library:
  source-dirs: src

executables:
  cellular:
    main:                Cellular
    source-dirs:         app
    ghc-options: -O2
    dependencies:
    - automata

# tests:
#   automata-test:
#     main:                Spec.hs
#     source-dirs:         test
#     dependencies:
#     - automata
